version: 0.2

env:
  variables:
    NODE_VERSION: "20"
    SST_TELEMETRY_DISABLED: "1"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci

  build:
    commands:
      - echo "Deploying with SST to stage $STAGE..."
      - npx sst deploy --stage ${STAGE:-dev}

  post_build:
    commands:
      - echo "Deployment complete"
      - echo "Build completed on $(date)"

artifacts:
  files:
    - '**/*'
  discard-paths: no

cache:
  paths:
    - 'node_modules/**/*'
    - '.sst/**/*'
